on: [push]
jobs:
 first_demo_job:
  name: The first demo job
  steps:
   -name: show the demo running
   env:
    VAR1: This is
    VAR2: A Demo of
    VAR3: Github Actions
    VAR4: Workflow jobs
   run:|
    echo $VAR1 $VAR2 $VAR3 $VAR4

